[tool.ruff]
select = [
  "B",    # flake8-bugbear
  "C4",   # flake8-comprehensions
  "C90",  # McCabe cyclomatic complexity
  "E",    # pycodestyle
  "EXE",  # flake8-executable
  "F",    # Pyflakes
  "I",    # isort
  "ICN",  # flake8-import-conventions
  "INT",  # flake8-gettext
  "ISC",  # flake8-implicit-str-concat
  "PIE",  # flake8-pie
  "PL",   # Pylint
  "PT",   # flake8-pytest-style
  "PYI",  # flake8-pyi
  "RSE",  # flake8-raise
  "RUF",  # Ruff-specific rules
  "S",    # flake8-bandit
  "SLF",  # flake8-self
  "T10",  # flake8-debugger
  "TID",  # flake8-tidy-imports
  "UP",   # pyupgrade
  "W",    # pycodestyle
  "YTT",  # flake8-2020
  # "A",    # flake8-builtins
  # "ANN",  # flake8-annotations
  # "ARG",  # flake8-unused-arguments
  # "BLE",  # flake8-blind-except
  # "COM",  # flake8-commas
  # "D",    # pydocstyle
  # "DJ",   # flake8-django
  # "DTZ",  # flake8-datetimez
  # "EM",   # flake8-errmsg
  # "ERA",  # eradicate
  # "FBT",  # flake8-boolean-trap
  # "G",    # flake8-logging-format
  # "INP",  # flake8-no-pep420
  # "N",    # pep8-naming
  # "NPY",  # NumPy-specific rules
  # "PD",   # pandas-vet
  # "PGH",  # pygrep-hooks
  # "PTH",  # flake8-use-pathlib
  # "Q",    # flake8-quotes
  # "RET",  # flake8-return
  # "SIM",  # flake8-simplify
  # "T20",  # flake8-print
  # "TCH",  # flake8-type-checking
  # "TRY",  # tryceratops
]
ignore = [
  "B904",
  "F401",
  "F841",
  "PLC1901",
  "PLR2004",
  "PLR5501",
  "PLW0603",
  "PLW2901",
  "RUF001",
  "RUF005",
  "S101",
  "S103",
  "S105",
  "S106",
  "S318",
  "S324",
]
target-version = "py37"

line-length = 102

[tool.ruff.mccabe]
max-complexity = 33

[tool.ruff.pylint]
max-args = 24
max-branches = 33
max-statements = 124

[tool.ruff.per-file-ignores]
"__init__.py" = ["E402"]
"tests/*" = ["PT017", "S101"]
"tests/cli/test_ia_list.py" = ["E741"]
"tests/test_api.py" = ["E712"]
"tests/test_config.py" = ["PT011"]
